#!/usr/bin/env python3
"""Generate matching offline and website policies from docs/PRIVACY.md."""
import argparse
import html
import json
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
source = (root / 'docs/PRIVACY.md').read_text()
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='Fail if generated policies are out of date')
args = parser.parse_args()
name = json.loads((root / 'app/AppScope/resources/base/element/string.json').read_text())['string'][0]['value']
if not source.startswith(f'# {name}隐私政策\n'):
    raise SystemExit('The policy and launcher application names must match')
revision = re.search(r'更新日期：(\d{4}) 年 (\d{1,2}) 月 (\d{1,2}) 日', source)
if revision is None:
    raise SystemExit('The policy must declare its update date')
version = '-'.join(value.zfill(2) for value in revision.groups())
parts = []
blocks = []
for block in source.strip().split('\n\n'):
    plain = re.sub(r'\[([^]]+)\]\((https://[^)]+|mailto:[^)]+)\)', r'\1（\2）', block)
    blocks.append({'heading': plain.startswith('#'), 'text': re.sub(r'^#{1,2} ', '', plain)})
    text = html.escape(block)
    text = re.sub(r'\[([^]]+)\]\((https://[^)]+|mailto:[^)]+)\)', r'<a href="\2">\1</a>', text)
    if text.startswith('# '):
        parts.append('<h1>' + text[2:] + '</h1>')
    elif text.startswith('## '):
        anchor = 'rights' if '你的权利' in text else 'section-' + text[3]
        parts.append(f'<h2 id="{anchor}">' + text[3:] + '</h2>')
    else:
        parts.append('<p>' + text + '</p>')
style = ('body{margin:0;background:#f1f3f5;color:#182431;font:16px/1.85 system-ui,-apple-system,"Segoe UI",sans-serif}'
         'main{max-width:800px;margin:0 auto;padding:48px 24px 72px}'
         'h1{font-size:32px;color:#0a59f7;line-height:1.4}h2{font-size:22px;margin:36px 0 12px;scroll-margin-top:24px}'
         'p{overflow-wrap:anywhere}a{color:#0a59f7;text-underline-offset:3px}nav{margin-bottom:28px}'
         'footer{border-top:1px solid #d9dde3;margin-top:40px;padding-top:20px;font-size:14px}')
document = ('<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width, initial-scale=1">'
            f'<meta name="color-scheme" content="light"><title>{html.escape(name)}隐私政策 · linloir</title>'
            f'<meta name="description" content="{html.escape(name)}的数据处理、隐私权利和联系方式。">'
            '<style>' + style + f'</style></head><body><main><nav><a href="../">{html.escape(name)}</a></nav>\n'
            + '\n'.join(parts) + '\n<footer>本页面不包含统计脚本、广告或 Cookie。</footer></main></body></html>\n')
offline = ('// Generated by scripts/build-site.py from docs/PRIVACY.md; do not edit.\n'
           'export interface PrivacyBlock { heading: boolean; text: string; }\n\n'
           f"export const PRIVACY_VERSION = '{version}';\n\n"
           'export const PRIVACY_BLOCKS: PrivacyBlock[] = '
           + json.dumps(blocks, ensure_ascii=False, indent=2) + ';\n')
for relative, content in [('site/privacy/index.html', document),
                          ('app/entry/src/main/ets/common/PrivacyContent.ets', offline)]:
    target = root / relative
    if args.check:
        if not target.is_file() or target.read_text() != content:
            raise SystemExit(f'Generated policy is stale: {relative}; run scripts/build-site.py')
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
    print(('Checked: ' if args.check else 'Generated: ') + relative)
